import { Request, Response, NextFunction } from "express";
import ordersService from "../services/orders.service";

import { sendJsonSuccess } from "../helpers/responseHandler";

const findAll = async (req: Request, res: Response, next: NextFunction) => {
  try {
    // Láº¥y data tá»« lá»›p service
    const orders = await ordersService.findAllOrder(req.query);
    console.log("<<=== ðŸš€findAll orders  ===>>", orders);
    //Tráº£ láº¡i cho client
    // res.status(200).json({
    //   data: orders
    // })
    sendJsonSuccess(res, "success")(orders);
  } catch (error) {
    next(error);
  }
};
const findById = async (req: Request, res: Response, next: NextFunction) => {
  try {
    const { id } = req.params;
    const order = await ordersService.findById(id);
    sendJsonSuccess(res, "success")(order);
  } catch (error) {
    next(error);
  }
};
const createRecord = async (
  req: Request,
  res: Response,
  next: NextFunction
) => {
  try {
    console.log("req.body ===>>", req.body);
    console.log("res.locals.customer ===>>", res.locals.customer);

    const order = await ordersService.createRecordOrder(
      req.body,
      res.locals.customer
    );

    sendJsonSuccess(res, "success", 201)(order);
  } catch (error) {
    next(error);
  }
};
const updateById = async (req: Request, res: Response, next: NextFunction) => {
  try {
    const { id } = req.params;
    const order = await ordersService.updateById(id, req.body);
    //ThÃ nh cÃ´ng
    sendJsonSuccess(res, "success", 200)(order);
  } catch (error) {
    //Chuyá»ƒn lá»—i qua cho handler error trong app.ts xá»­ lÃ½
    next(error);
  }
};
const deleteById = async (req: Request, res: Response, next: NextFunction) => {
  try {
    const { id } = req.params;
    const order = await ordersService.deleteById(id);
    sendJsonSuccess(res, "success", 200)(order);
  } catch (error) {
    next(error);
  }
};
export default {
  findAll,
  findById,
  createRecord,
  updateById,
  deleteById,
};
